title: Nagendra Palla 
logo: /assets/img/logo.jfif


description:
I am AI/ML engineer 
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
